# Generated by Django 5.0.14 on 2026-07-18 19:37

import django.db.models.deletion
from django.db import migrations, models


def delete_all_cartitems(apps, schema_editor):
    CartItem = apps.get_model('cart', 'CartItem')
    CartItem.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0008_productvariant'),
    ]

    operations = [
        migrations.RunPython(delete_all_cartitems, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'variant')},
        ),
    ]
