# Generated by Django 5.0.14 on 2026-07-18 19:51

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.products.models.product_image_upload_to),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.products.models.variant_image_upload_to),
        ),
    ]
